name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: echo SSH key
        run: |
          ls -la > "scptest.txt"
          scp -P 9114 scptest.txt root@www.lionhaert.pe.kr:/home/father
        shell: bash
        env:
          SIP :  ${{ secrets.REMOTE_IP }} 
          SID :  ${{ secrets.REMOTE_SSH_ID }}
          SKEY :  ${{ secrets.REMOTE_SSH_KEY }}
          SPORT :  ${{ secrets.REMOTE_SSH_PORT }}
