name: echo 5

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

      runs-on: ubuntu-latest

    steps:
    - name: "현재경로"
      run : pwd

    - name: "아이피"
      run : echo ${{ secrets.REMOTE_IP }} 

    - name: "ssh ID"
      run : echo ${{ secrets.REMOTE_SSH_ID }}

    - name: "ssh KEY"
      run : echo ${{ secrets.REMOTE_SSH_KEY }}
